### PR TITLE
feat: rehype-remove-images

### PR DESCRIPTION
**Pull request by iloveitaly**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [ ] If applicable, I’ve added docs and tests

### Description of changes

Simple plugin to remove images from HTML.

The typing syntax feels strange compared to normal typescript, so the build is failing. Before digging further, I wanted to submit a draft PR
to see if this is something you'd like to include in the package.

If you could point me in the right direction to fix up the TS issues / understand the new TS syntax I', seeing here I'd be grateful.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@wooorm this PR isn't ready yet, but I'm curious if you could point me in the right direction to fix up this PR.

**Review by wooorm — COMMENTED** [review]
Hi there!

I wonder if this is the place to maintain this.
Typically images are semantic: they have meaning to the document.
This project performs changes that typically remain equal to the original input.

Like many other rehype plugins, I think you can maintain this separately?

As for this PR:

* the code style doesn’t yet match the project, run `npm test` to solve that, it generates the `readme` too
* as for type issues, I think the only thing is that you create a project that does not accept options? so you’d need ` * @type {import('unified').Plugin<[], Root>}`
  for more on how types through JSDoc work, see https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html, https://github.com/voxpelli/types-in-js
* `visit` is much more powerful, and simpler, than `remove`. Here’s an example of what you want to do:
  ```ts
  import type {Nodes} from 'hast'
  import {visit} from 'unist-util-visit'

  const tree: Nodes = getNodeSomehow()

  visit(tree, function (node, index, parent) {
    if (parent && index !== undefined && node.type === 'element' && node.tagName === 'img') {
      parent.children.splice(index, 1)
      return index
    }
  })
  ```

**Comment by iloveitaly** [comment]
@wooorm thanks for the helpful response!

Do you think I should just pull this into a separate repo, or would you be open to including it here if the issues were fixed?

**Comment by wooorm** [comment]
The former, as of yet I don’t feel like it fits here, but maybe you have good reasons to say it is useful to just *minify* without side-effects for most folks (opt-in or not).
So, make your own repo, PR to add it to the [list of plugins](https://github.com/rehypejs/rehype/blob/main/doc/plugins.md), and ask for a review on tips! (or feel free to open discussions earlier!)

**Pull request closed without merging**
